#!/bin/sh

if ! type commitlint >/dev/null 2>/dev/null; then
	echo ""
  echo "commitlint could not be found"
  echo "try again after installing commitlint or add commitlint to PATH"
  echo "go install github.com/conventionalcommit/commitlint@latest"
	echo ""
  exit 2;
fi

commitlint lint --message $1
