version: "2"

linters:
  default: none
  enable:
    - govet
    - whitespace
    - gosec
    - godox
    - gocyclo
  allow-parallel-runners: true

linters-settings:
  godox:
    keywords:
      - FIX
      - HACK
  gocyclo:
    min-complexity: 8

issues:
  exclude-files:
    - ^test_.*\.go$
