name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  commit_lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Up GoLang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install commitlint
      run: go install github.com/conventionalcommit/commitlint@latest

    - name: Commit Lint Last Commit
      if: github.event_name == 'push'
      run: |
        git show -s --format=%s | commitlint lint
    - name: Commit Lint PR
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin
        git checkout origin/${{ github.head_ref }}
        BASE_COMMIT=$(git rev-parse origin/${{ github.base_ref }}~1)
        git log --pretty=format:"%H" $BASE_COMMIT..HEAD | while read commit_hash; do
          echo "Linting commit: $commit_hash"
          git show -s --format=%s "$commit_hash" | commitlint lint
          if [ $? -ne 0 ]; then
            echo "::error::Commit linting failed for commit $commit_hash"
            exit 1
          fi
          echo "----------------------------------------"
        done
  code_lint:
    runs-on: ubuntu-latest
    needs: commit_lint

    steps:
    - uses: actions/checkout@v4

    - name: Set Up GoLang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install golangci-lint
      run: |
        curl -sSL https://github.com/golangci/golangci-lint/releases/download/v2.1.2/golangci-lint-2.1.2-linux-amd64.tar.gz \
          | tar -xz

        sudo mv golangci-lint-2.1.2-linux-amd64/golangci-lint /usr/local/bin/

        golangci-lint --version


    - name: Run Code Lint
      id: code_lint
      run: |
        make lint
  test:
    runs-on: ubuntu-latest
    needs: code_lint

    steps:
    - uses: actions/checkout@v4

    - name: Set Up GoLang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run Coverage
      id: coverage
      run: |
        make coverage
        coverage_output=$(make coverage-inspect-text)
        echo "--------------------------------------------------------------------------------"
        echo "$coverage_output"
        echo "--------------------------------------------------------------------------------"
        # Extract the percentage (assuming it's the last number followed by %)
        COVERAGE_PERCENTAGE=$(echo "$coverage_output" | grep -oE '[0-9]+\.[0-9]+%' | tail -n 1 | sed 's/%//')
        echo "COVERAGE_PERCENTAGE=$COVERAGE_PERCENTAGE" >> "$GITHUB_OUTPUT"
    - name: Verify Coverage
      if: steps.coverage.outputs.COVERAGE_PERCENTAGE < 90
      run: |
        echo "Code coverage is below 90% (${{ steps.coverage.outputs.COVERAGE_PERCENTAGE }}%). Failing the build."
        exit 1
    - name: Coverage Success
      if: steps.coverage.outputs.COVERAGE_PERCENTAGE >= 90
      run: |
        echo "Code coverage is at or above 90% (${{ steps.coverage.outputs.COVERAGE_PERCENTAGE }}%)."
